org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.1-SNAPSHOT
project.libs.versions.neoforgedatapackextensions=21.11.3
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=Bad dreams? Configure your sleeping experience to your desires.
mod.group=fuzs.letmesleep
mod.id=letmesleep
mod.license=MPL-2.0
mod.name=Let Me Sleep
mod.version=26.1.0

dependencies.common.multiloaderdataextensions=embedded
dependencies.fabric.fabricapi=required
dependencies.fabric.forgeconfigapiport=required
dependencies.fabric.puzzleslib=required
dependencies.neoforge.puzzleslib=required

distributions.github.slug=let-me-sleep

environments.client=optional
environments.server=required
