org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.1-SNAPSHOT
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=Monsters are keeping you awake? Customize sleeping, waking, and bed mechanics freely.
mod.group=fuzs.letmesleep
mod.id=letmesleep
mod.license=MPL-2.0
mod.name=Let Me Sleep
mod.version=26.1.0

dependencies.common.multiloaderdataextensions=embedded
dependencies.fabric.fabricapi=required
dependencies.fabric.forgeconfigapiport=required
dependencies.fabric.puzzleslib=required
dependencies.neoforge.puzzleslib=required

distributions.curseforge.id=322764
distributions.curseforge.slug=let-me-sleep
distributions.github.slug=let-me-sleep
distributions.modrinth.id=KK4HJa9m
distributions.modrinth.slug=new-let-me-sleep

environments.client=optional
environments.server=required
